Install numpy package - pip install numpy
(a powerful library for numerical computing in Python)

In [12]:
import numpy as np
print(np.sqrt(49))
print(np.power(2,3))
print(np.round(2.3))
print(np.sin(np.radians(30)))#convert radians and calcutale
print(np.log(100))

7.0
8
2.0
0.49999999999999994
4.605170185988092


In [1]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [6]:
arr2=np.array([[1,2,3,],[2,4,7],[2,3,4]])
print(arr2)

[[1 2 3]
 [2 4 7]
 [2 3 4]]


In [4]:
arr3=arr1+arr1
print(arr3)

[ 2  4  6  8 10]


In [7]:
shape=arr2.shape
print(shape)

(3, 3)


In [11]:
new=np.array([1,2,3,4,5,6,7,8,9])
b=new.reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
b[1,2]

6

In [13]:
b.sum

<function ndarray.sum>